global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using MechanicService.Domain.Entities;
global using MechanicService.Application.Interfaces;
global using MechanicService.Persistence.Context;
global using System.Linq.Expressions;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.EntityFrameworkCore.Infrastructure;

global using MechanicService.Application.Interfaces.ReservationInterfaces;
global using MechanicService.Application.Interfaces.LocationsInterfaces;
global using MechanicService.Application.Interfaces.CarModelnterfaces;
global using MechanicService.Application.Interfaces.StatisticsInterfaces;
global using MechanicService.Application.Interfaces.CustomerInterfaces;
global using MechanicService.Application.Interfaces.BlogInterfaces;
global using MechanicService.Application.ViewModel;